import keyMirror from 'keymirror';

export default keyMirror({
  REQUEST_BRANCHES_IN_REPO: null,
  RECEIVE_BRANCHES_IN_REPO: null,
  REQUEST_BRANCH_INFO: null,
  RECEIVE_BRANCH_INFO: null,

  REQUEST_MODULE_STATES: null,
  RECEIVE_MODULE_STATES: null,
  SELECT_MODULE: null,
  DESELECT_MODULE: null,
  SELECT_MODULE_BUILD_HISTORY_PAGE: null,

  REQUEST_MODULE_BUILD_HISTORY: null,
  RECEIVE_MODULE_BUILD_HISTORY: null,

  TOGGLE_STARRED_BRANCH: null
});
