import keyMirror from 'keymirror';

export default keyMirror({
  START_POLLING_BRANCH_STATUS: null,
  STOP_POLLING_BRANCH_STATUS: null,
  RECEIVE_BRANCH_STATUS: null,

  SELECT_MODULE: null,
  DESELECT_MODULE: null,

  SELECT_MODULE_BUILD_HISTORY_PAGE: null,
  REQUEST_MODULE_BUILD_HISTORY: null,
  RECEIVE_MODULE_BUILD_HISTORY: null,

  TOGGLE_STARRED_BRANCH: null,
  SYNC_STARRED_BRANCHES: null,

  SHOW_BUILD_BRANCH_MODAL: null,
  HIDE_BUILD_BRANCH_MODAL: null,
  UPDATE_BRANCH_BUILD_SELECTED_MODULE_IDS: null,
  TOGGLE_BUILD_DOWNSTREAM_MODULES: null,
  TOGGLE_TRIGGER_INTERPROJECT_BUILD: null,
  TOGGLE_RESET_CACHE: null,
  RECEIVE_TRIGGER_BUILD_ERROR: null,

  DISMISS_BRANCH_STATE_PAGE_BETA_NOTIFICATION: null
});
