import keyMirror from 'keymirror';

export default keyMirror({
  REQUEST_BRANCHES_IN_REPO: null,
  RECEIVE_BRANCHES_IN_REPO: null,
  REQUEST_BRANCH_INFO: null,
  RECEIVE_BRANCH_INFO: null,

  START_POLLING_MODULE_STATES: null,
  STOP_POLLING_MODULE_STATES: null,
  RECEIVE_MODULE_STATES: null,
  SELECT_MODULE: null,
  DESELECT_MODULE: null,
  SELECT_MODULE_BUILD_HISTORY_PAGE: null,

  REQUEST_MODULE_BUILD_HISTORY: null,
  RECEIVE_MODULE_BUILD_HISTORY: null,

  TOGGLE_STARRED_BRANCH: null,
  SYNC_STARRED_BRANCHES: null,

  SHOW_BUILD_BRANCH_MODAL: null,
  HIDE_BUILD_BRANCH_MODAL: null,
  UPDATE_BRANCH_BUILD_SELECTED_MODULE_IDS: null,
  TOGGLE_BUILD_DOWNSTREAM_MODULES: null,
  TOGGLE_TRIGGER_INTERPROJECT_BUILD: null,
  TOGGLE_RESET_CACHE: null,
  RECEIVE_TRIGGER_BUILD_ERROR: null
});
